import type { Dashboard } from "../features/projects/types";

export const demoDashboard: Dashboard = {
  refreshedAt: "2026-07-13T13:24:00Z",
  projects: [
    {
      project: {
        id: "orion-demo",
        name: "Orion",
        path: "C:\\Projects\\Orion",
        goal: "Make every project instantly understandable and easy to resume.",
        nextAction: "Verify the first native project-import loop.",
        status: "active",
        createdAt: "2026-07-13T09:00:00Z",
        updatedAt: "2026-07-13T13:24:00Z",
      },
      features: [
        {
          id: "f-overview",
          projectId: "orion-demo",
          name: "Project constellation",
          description: "A scan-friendly overview of every registered application.",
          status: "working",
          priority: "now",
          evidence: "Dashboard projections covered by unit tests.",
          createdAt: "2026-07-13T09:00:00Z",
          updatedAt: "2026-07-13T13:20:00Z",
        },
        {
          id: "f-git",
          projectId: "orion-demo",
          name: "Git telemetry",
          description: "Branches, commits, divergence, and working-tree changes.",
          status: "in_progress",
          priority: "now",
          evidence: "Native command implemented; artifact verification pending.",
          createdAt: "2026-07-13T09:00:00Z",
          updatedAt: "2026-07-13T13:10:00Z",
        },
        {
          id: "f-ai",
          projectId: "orion-demo",
          name: "Local project analyst",
          description: "Proposes feature and next-step updates for confirmation.",
          status: "planned",
          priority: "later",
          evidence: "Intentionally outside the MVP.",
          createdAt: "2026-07-13T09:00:00Z",
          updatedAt: "2026-07-13T09:00:00Z",
        },
      ],
      focuses: [
        {
          id: "focus-orion",
          projectId: "orion-demo",
          title: "Verify the first native project-import loop",
          status: "active",
          startedAt: "2026-07-13T11:00:00Z",
          endedAt: null,
        },
      ],
      tasks: [
        {
          id: "t-map",
          projectId: "orion-demo",
          focusId: "focus-orion",
          featureId: "f-overview",
          title: "Turn the project cockpit into a visual mission map",
          completed: false,
          createdAt: "2026-07-13T13:25:00Z",
          updatedAt: "2026-07-13T13:25:00Z",
        },
        {
          id: "t-native",
          projectId: "orion-demo",
          focusId: "focus-orion",
          featureId: "f-git",
          title: "Verify the exact packaged Orion.exe",
          completed: false,
          createdAt: "2026-07-13T13:18:00Z",
          updatedAt: "2026-07-13T13:18:00Z",
        },
        {
          id: "t-import",
          projectId: "orion-demo",
          focusId: "focus-orion",
          featureId: "f-overview",
          title: "Connect the native repository picker",
          completed: true,
          createdAt: "2026-07-13T11:00:00Z",
          updatedAt: "2026-07-13T13:10:00Z",
        },
      ],
      git: {
        available: true,
        error: null,
        currentBranch: "feat/project-cockpit",
        upstream: "origin/feat/project-cockpit",
        ahead: 2,
        behind: 0,
        modifiedFiles: 7,
        isDirty: true,
        branches: [
          {
            name: "feat/project-cockpit",
            shortHash: "7df2a91",
            updatedAt: "2026-07-13T13:17:00Z",
            isCurrent: true,
          },
          {
            name: "main",
            shortHash: "5b0e421",
            updatedAt: "2026-07-12T18:40:00Z",
            isCurrent: false,
          },
        ],
        commits: [
          {
            hash: "7df2a91e9510",
            shortHash: "7df2a91",
            subject: "Build project cockpit and feature matrix",
            authoredAt: "2026-07-13T13:17:00Z",
            author: "Demo User",
            changedFiles: 6,
            additions: 184,
            deletions: 31,
          },
          {
            hash: "0e2a8272b101",
            shortHash: "0e2a827",
            subject: "Add local repository snapshot command",
            authoredAt: "2026-07-13T11:46:00Z",
            author: "Demo User",
            changedFiles: 4,
            additions: 112,
            deletions: 9,
          },
          {
            hash: "5b0e42118f20",
            shortHash: "5b0e421",
            subject: "Define Orion product contract",
            authoredAt: "2026-07-12T18:40:00Z",
            author: "Demo User",
            changedFiles: 3,
            additions: 76,
            deletions: 2,
          },
        ],
      },
    },
    {
      project: {
        id: "menma-demo",
        name: "Menma",
        path: "C:\\Projects\\Nebula Notes",
        goal: "Create a living story workspace with coherent characters.",
        nextAction: "Connect the story room to a selected local model.",
        status: "active",
        createdAt: "2026-07-01T10:00:00Z",
        updatedAt: "2026-07-12T19:00:00Z",
      },
      features: [
        {
          id: "m-story",
          projectId: "menma-demo",
          name: "Story room",
          description: "Core narrative workspace.",
          status: "working",
          priority: "now",
          evidence: "Reducer and roster tests pass.",
          createdAt: "2026-07-01T10:00:00Z",
          updatedAt: "2026-07-12T19:00:00Z",
        },
        {
          id: "m-model",
          projectId: "menma-demo",
          name: "LM Studio connection",
          description: "Select and call an available local model.",
          status: "blocked",
          priority: "now",
          evidence: "Model-selection UX is not connected yet.",
          createdAt: "2026-07-01T10:00:00Z",
          updatedAt: "2026-07-12T19:00:00Z",
        },
      ],
      focuses: [
        {
          id: "focus-menma",
          projectId: "menma-demo",
          title: "Connect the story room to a selected local model",
          status: "active",
          startedAt: "2026-07-12T19:00:00Z",
          endedAt: null,
        },
      ],
      tasks: [
        {
          id: "m-task-model",
          projectId: "menma-demo",
          focusId: "focus-menma",
          featureId: "m-model",
          title: "Connect the story room to the selected local model",
          completed: false,
          createdAt: "2026-07-12T19:05:00Z",
          updatedAt: "2026-07-12T19:05:00Z",
        },
      ],
      git: {
        available: true,
        error: null,
        currentBranch: "main",
        upstream: "origin/main",
        ahead: 0,
        behind: 0,
        modifiedFiles: 0,
        isDirty: false,
        branches: [
          {
            name: "main",
            shortHash: "819dc4a",
            updatedAt: "2026-07-12T19:00:00Z",
            isCurrent: true,
          },
        ],
        commits: [
          {
            hash: "819dc4a6fe11",
            shortHash: "819dc4a",
            subject: "Add model status and roster coverage",
            authoredAt: "2026-07-12T19:00:00Z",
            author: "Demo User",
            changedFiles: 5,
            additions: 98,
            deletions: 18,
          },
        ],
      },
    },
  ],
};
